{
  "_args": [
    [
      "bounce@https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
      "/home/thiago/Documentos/Dev/Courses/nodejs/17-hapi-atualizar-joi/node_modules/hapi"
    ]
  ],
  "_from": "bounce@https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
  "_id": "bounce@1.2.3",
  "_inCache": true,
  "_location": "/hapi/bounce",
  "_phantomChildren": {},
  "_requested": {
    "name": "bounce",
    "raw": "bounce@https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
    "rawSpec": "https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
    "scope": null,
    "spec": "https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
    "type": "remote"
  },
  "_requiredBy": [
    "/hapi",
    "/hapi/somever",
    "/hapi/statehood"
  ],
  "_resolved": "https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
  "_shasum": "2b286d36eb21d5f08fe672dd8cd37a109baad121",
  "_shrinkwrap": null,
  "_spec": "bounce@https://registry.npmjs.org/bounce/-/bounce-1.2.3.tgz",
  "_where": "/home/thiago/Documentos/Dev/Courses/nodejs/17-hapi-atualizar-joi/node_modules/hapi",
  "bugs": {
    "url": "https://github.com/hapijs/bounce/issues"
  },
  "dependencies": {
    "boom": "7.x.x",
    "hoek": "6.x.x"
  },
  "description": "Selective error catching and rewrite rules",
  "devDependencies": {
    "code": "5.x.x",
    "lab": "17.x.x"
  },
  "homepage": "https://github.com/hapijs/bounce#readme",
  "keywords": [
    "catch",
    "error"
  ],
  "license": "BSD-3-Clause",
  "main": "lib/index.js",
  "name": "bounce",
  "optionalDependencies": {},
  "readme": "# bounce\r\n\r\nSelective error catching and rewrite rules\r\n\r\n[![Build Status](https://secure.travis-ci.org/hapijs/bounce.svg)](http://travis-ci.org/hapijs/bounce)\r\n\r\nLead Maintainer - [Eran Hammer](https://github.com/hueniverse)\r\n\r\n## Introduction\r\n\r\nWorking with `async`/`await` introduces a new challange in handling errors. Unlike callbacks, which\r\nprovide a dual mechanism for passing application errors via the callback `err` argument and\r\ndeveloper errors via exceptions, `await` combines these two channels into one.\r\n\r\nIt is common practice to ignore application errors in background processing or when there is no\r\nuseful fallback. In those cases, it is still imperative to allow developer errors to surface and\r\nnot get swallowed.\r\n\r\nFor more information read:\r\n- [Learning to Throw Again](https://medium.com/@eranhammer/learning-to-throw-again-79b498504d28)\r\n- [Catching without Awaiting](https://medium.com/@eranhammer/catching-without-awaiting-b2cb7df45790)\r\n\r\nFor example:\r\n\r\n```js\r\nasync function email(user) {\r\n\r\n    if (!user.address) {\r\n        throw new Error('User has no email address');\r\n    }\r\n\r\n    const message = 'Welcome!';\r\n    if (user.name) {\r\n        message = `Welcome ${user.name}!`;\r\n    }\r\n\r\n    await mailer.send(user.address, message);\r\n}\r\n\r\nasync function register(address, name) {\r\n\r\n    const user = { address, name };\r\n    const id = await db.user.insert(user);\r\n    user.id = id;\r\n\r\n    try {\r\n        await email(user);\r\n    }\r\n    catch (err) { }             // Ignore errors\r\n\r\n    return user;\r\n}\r\n```\r\n\r\nThis will fail silently every time the user has a `name` because it is reassigning a value to a\r\n`const` variable. However, because `email()` errors are ignored, system errors are ignored as well.\r\nThe idea is that `email()` can be used in both critical and non-critical paths. In the critical\r\npaths, errors are checked and addressed, but in the non-critical paths, errors are simply ignored.\r\n\r\nThis can be solved by adding a `rethrow()` statement:\r\n\r\n```js\r\nconst Bounce = require('bounce');\r\n\r\nasync function register(address, name) {\r\n\r\n    const user = { address, name };\r\n    const id = await db.user.insert(user);\r\n    user.id = id;\r\n\r\n    try {\r\n        await email(user);\r\n    }\r\n    catch (err) {\r\n        Bounce.rethrow(err, 'system');  // Rethrows system errors and ignores application errors\r\n    }\r\n\r\n    return user;\r\n}\r\n```\r\n\r\n## Usage\r\n\r\n### `rethrow(err, types, [options])`\r\n\r\nThrows the error passed if it matches any of the specified rules where:\r\n- `err` - the error.\r\n- `type` - a single item or an array of items of:\r\n    - An error constructor (e.g. `SyntaxError`).\r\n    - `'system'` - matches any languange native error or node assertions.\r\n    - `'boom'` - matches [**boom**](https://github.com/hapijs/boom) errors.\r\n    - an object where each property is compared with the error and must match the error property\r\n      value. All the properties in the object must match the error but do not need to include all\r\n      the error properties.\r\n- `options` - optional object where:\r\n    - `decorate` - an object which is assigned to the `err`, copying the properties onto the error.\r\n    - `override` - an error used to override `err` when `err` matches. If used with `decorate`,\r\n      the `override` object is modified.\r\n    - `return` - if `true`, the error is returned instead of thrown. Defaults to `false`.\r\n\r\n### `ignore(err, types, [options])`\r\n\r\nThe opposite action of `rethrow()`. Ignores any errors matching the specified `types`. Any error\r\nnot matching is thrown after applying the `options`.\r\n\r\n### `background(operation, [action], [types], [options])`\r\n\r\nAwaits for the value to resolve in the background and then apply either the `rethrow()` or `ignore()`\r\nactions where:\r\n- `operation` - a function, promise, or value that is `await`ed on inside a `try...catch` and any\r\n  error thrown processed by the `action` rule.\r\n- `action` - one of `'rethrow'` or `'ignore'`. Defaults to `'rethrow'`.\r\n- `types` - same as the `types` argument passed to `rethrow()` or `ignore()`. Defaults to `'system'`.\r\n- `options` - same as the `options` argument passed to `rethrow()` or `ignore()`.\r\n\r\n### `isBoom(err)`\r\n\r\nReturns `true` when `err` is a [**boom**](https://github.com/hapijs/boom) error.\r\n\r\n### `isError(err)`\r\n\r\nReturns `true` when `err` is an error.\r\n\r\n### `isSystem(err)`\r\n\r\nReturn `true` when `err` is one of:\r\n- `EvalError`\r\n- `RangeError`\r\n- `ReferenceError`\r\n- `SyntaxError`\r\n- `TypeError`\r\n- `URIError`\r\n- Node's `AssertionError`\r\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git://github.com/hapijs/bounce.git"
  },
  "scripts": {
    "test": "lab -a code -t 100 -L",
    "test-cov-html": "lab -a code -r html -o coverage.html -L"
  },
  "version": "1.2.3"
}
